import type { NextPage } from "next";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.css";

import { Container, Row, Col, Button } from "reactstrap";
import PageHandler from "common/page";
import Navbar from "common/navbar";
import { FormattedMessage } from "react-intl";
import { useRouter } from "next/router";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export async function getServerSideProps(cxt: any) {

  return {
    props: {

      lang: cxt.params.lang,
    },
  };
}

const Page: NextPage = (props) => {
  const { lang } = props as any;
  const router = useRouter();
  return (
    <PageHandler lang={lang}>
      <Head>
        <title>Support restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar lang={lang} pathname={ router.asPath} tag={null} />
      <Container className="mt-4">
        <Row>
          <Col>
            <p>
              <FormattedMessage id="msg.intro" />{" "}
              <b>
                <a href="https://wck.org/" target="_blank">
                  World Central Kitchen
                </a>
              </b>
            </p>
            <p>
              <FormattedMessage id="msg.goal" />
            </p>
            <p>
              <FormattedMessage id="msg.cta" />
            </p>
          </Col>
        </Row>
        <Row>
          <Col className="text-center">
            <Button
              className="text-capitalize"
              color="success"
              onClick={() => {
                window.open(
                  `https://donate.wck.org/give/f3789323/#!/donation/checkout`,
                  "_blank"
                );
              }}
            >
              <FormattedMessage id="app.donate" />
            </Button>
          </Col>
        </Row>
      </Container>
    </PageHandler>
  );
};

export default Page;
