version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $DOCKER_AUTH
      - pwd
      - ls
      - echo node -v
      - node -v
      - echo docker -v
      - docker -v
      - npm update -g npm
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
      - mkdir ~/build 
  pre_build:
    commands:
      - export SCOPE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Installing source NPM dependencies...
      - yarn --cwd ./backend install
      - yarn --cwd ./backend build 
      - yarn --cwd ./deployment/publish install 
  build:
    commands:
      - echo Build started on `date`
      - yarn --cwd ./deployment/build install 
      - yarn --cwd ./deployment/build start 
  post_build:
    commands:
      - echo Build completed on `date`
      - yarn --cwd ./deployment/publish start 
artifacts:
  files:
    - '$BUILD_TARGET_PATH/artifact-output/**/*'
  secondary-artifacts:
    BuildArtifact:
      files:
        - '$BUILD_TARGET_PATH/artifact-output/**/*'
#    appSpec:
#      files:
#        - '$BUILD_TARGET_PATH/artifact-output/application/**/*'
#      discard-paths: yes
