version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - pwd
      - ls
      - echo node -v
      - node -v
      - npm update -g npm
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn --cwd ./deployment/build install 
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn --cwd ./deployment/build start 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Distributing to S3...