version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - pwd
      - ls
      - echo node -v
      - node -v
      - echo docker -v
      - docker -v
      - npm update -g npm
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
      - mkdir ~/.docker && echo "{\n\t\"auths\": {\n\t\t\"https://index.docker.io/v1/\": {\n\t\t\t\"auth\": \"$DOCKER_AUTH\"\n\t\t}\n\t}\n}" > ~/.docker/config.json  
  pre_build:
    commands:
      - docker login -u repoflow
      - echo Installing source NPM dependencies...
      - yarn --cwd ./deployment/build install 
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn --cwd ./deployment/build start 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Distributing to S3...