version: '3'

services:
  data:
    image: bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      POSTGRES_USER: user
      POSTGRES_DB: prod-data
    volumes:
      - './data:/bitnami/postgresql'
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  backend:
    build:
      context: ./backend
    environment:
      - ENV_MODE=prod
      - PORT_SERVICE=4000
      - DATA_URL=data:5432
    volumes:
      - ./backend:/app
    depends_on:
      - data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  data-admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ;L;m8-L+B^8V4A}n
    ports:
      - "5050:80"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/log/:/var/log
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "hostdev:172.17.0.1"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
