import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.css";

import { Container, Row, Col, Badge } from "reactstrap";
import { RESTAURANT_LIST } from "common/queries/restaurant";
import client from "utils/client";
import PageHandler from "common/page";
import Navbar from "common/navbar";
import RestaurantContent from "common/restaurant/content";
import { FormattedMessage } from "react-intl";

export async function getServerSideProps(cxt) {
  const { data } = await client.query({
    query: RESTAURANT_LIST,
  });

  return {
    props: {
      list: data.viewer.account.restaurants.list,
      lang: cxt.params.lang,
    },
  };
}

const Home: NextPage = ({ list, lang }) => {
  return (
    <PageHandler lang={lang}>
      <Head>
        <title>Support restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar lang={lang} />
      <Container>
        {list.map((restaurant: any) => {
          const {
            id,
            name,
            images,
            description,
            receivedDonations,
          } = restaurant;
          return (
            <Row key={id} className="m-4">
              <RestaurantContent restaurant={restaurant} />
              <Col>
                <a
                  href={`/listing/${lang}/view/${id}`}
                  className="text-capitalize btn btn-primary"
                >
                  <FormattedMessage id="app.view" />
                </a>
              </Col>
            </Row>
          );
        })}
      </Container>
    </PageHandler>
  );
};

export default Home;
