FROM nginx:1.16-alpine

#BLOCK|prod
#ARG CACHEBUST=1
#RUN echo "CACHE $CACHEBUST"
#RUN mkdir -p /etc/nginx/sites-available
#COPY ./sites /etc/nginx/sites-available
#COPY ./nginx.conf /etc/nginx/nginx.conf
#prod

CMD ["nginx"]

EXPOSE 80 443
