version: '3'

services:
  nginx:
    build:
      context: ../../nginx
    volumes:
      - /home/victor/commit/user-data/commit-hop-support-restaurants/certificates/:/certificates
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../nginx/sites/:/etc/nginx/sites-available
    extra_hosts:
      - "hostdev:172.17.0.1"

