version: '3'

services:
  backend:
    build:
      context: ../../backend
    environment:
      - ENV_MODE=dev
      - PORT_SERVICE=4000
      - DATA_URL=postgres://postgres@data:5432/postgres
      - DATABASE_URL=postgres://postgres@data:5432/data
      - SEARCH_URL=http://admin:admin@opensearch-node:9200
      - SCOPE=dev
    volumes:
      - ../../backend:/app
  backend-static:
    environment:
      - NEXT_PUBLIC_SCOPE=dev
    build:
      context: ../../backend-static
    volumes:
      - ../../backend-static:/app
  nginx:
    build:
      context: ../../nginx
    volumes:
      - /home/victor/commit/user-data/certificates/:/certificates
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../nginx/sites/:/etc/nginx/sites-available
    extra_hosts:
      - "hostdev:172.17.0.1"

