version: '3'

networks: 
  default: 
    external: 
      name: ua-wck-network 
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
