import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.css";
import L from "leaflet";

import { Container, Row, Col, Badge } from "reactstrap";
import { RESTAURANT_LIST } from "common/queries/restaurant";
import { BORDERPOINT_LIST } from "common/queries/border-point";
import client from "utils/client";
import PageHandler, { pageConfig } from "common/page";
import Navbar from "common/navbar";
import { useRouter } from "next/router";

import dynamic from "next/dynamic";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const Map = dynamic(() => import("../../../components/map"), {
  ssr: false
});


export async function getServerSideProps(cxt: any) {
  pageConfig(cxt);

  const restaurantPromise = client.query({
    query: RESTAURANT_LIST,
    fetchPolicy: "no-cache"
  });

  const borderPromise = client.query({
    query: BORDERPOINT_LIST,
    fetchPolicy: "no-cache"
  });

  const [{ data: restaurantData }, { data: borderData }] = await Promise.all([restaurantPromise, borderPromise]);

  const markers = [{
    list: restaurantData.viewer.account.restaurants.list,
    icon: "blue",
    title: "app.restaurants",
    description: "app.restaurants-description"
  },
  {
    list: borderData.viewer.account.borderPoints.list,
    icon: "red",
    title: "app.distribution-points",
    description: "app.distribution-points-description"
  }]

  return {
    props: {
      markers,
      lang: cxt.params.lang,
    },
  };
}

const Page: NextPage = (props) => {
  const { markers, lang } = props as any;
  const router = useRouter();
  return (
    <PageHandler lang={lang}>
      <Head>
        <title>Support restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar lang={lang} pathname={router.asPath} tag={null} />
      <Map markers={markers} />
    </PageHandler>
  );
};

export default Page;
