import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.css";

import { Container, Row, Col, Badge } from "reactstrap";
import { RESTAURANT_GET } from "common/queries/restaurant";
import client from "utils/client";
import PageHandler, { pageConfig } from "common/page";
import Navbar from "common/navbar";
import RestaurantContent from "common/restaurant/content";
import { FormattedMessage } from "react-intl";
import { useRouter } from "next/router";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export async function getServerSideProps(cxt: any) {
  pageConfig(cxt);

  const { data } = await client.query({
    query: RESTAURANT_GET,
    variables: { id: cxt.params.id },
    fetchPolicy: "no-cache",
  });

  return {
    props: {
      restaurant: data.viewer.account.restaurants.get,
      lang: cxt.params.lang,
    },
  };
}

const View: NextPage = (props) => {
  const { restaurant, lang } = props as any;
  const router = useRouter();
  const { id, name, description, images, receivedDonations } = restaurant;

  return (
    <PageHandler lang={lang}>
      <Head>
        <title>Support restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar lang={lang} pathname={"/listing" + router.asPath} tag={null} />
      <Container>
        <Row key={id} className="m-4">
          <RestaurantContent restaurant={restaurant} />
          <Col>
            <a
              href={`/${lang}/donate`}
              className="text-capitalize btn btn-success"
            >
              <FormattedMessage id="app.donate" />
            </a>
          </Col>
        </Row>
      </Container>
    </PageHandler>
  );
};

export default View;
