import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.css";

import { Container, Row, Col, Badge } from "reactstrap";
import { RESTAURANT_GET } from "common/queries/restaurant";
import client from "utils/client";
import PageHandler from "common/page";
import Navbar from "common/navbar";
import RestaurantContent from "common/restaurant/content";
import { FormattedMessage } from "react-intl";

export async function getServerSideProps(cxt) {
  const { data } = await client.query({
    query: RESTAURANT_GET,
    variables: { id: cxt.params.id },
  });

  return {
    props: {
      restaurant: data.viewer.account.restaurants.get,
      lang: cxt.params.lang,
    },
  };
}

const View: NextPage = ({ restaurant, lang }) => {
  const { id, name, description, images, receivedDonations } = restaurant;

  return (
    <PageHandler lang={lang}>
      <Head>
        <title>Support restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar lang={lang} />
      <Container>
        <Row key={id} className="m-4">
          <RestaurantContent restaurant={restaurant} />
        </Row>
      </Container>
    </PageHandler>
  );
};

export default View;
